// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxaFkZlJuRLp0kovt0Q9iAMkRU7WbVmA',
    appId: '1:1027139795680:web:f8c084f62dde9b65776e85',
    messagingSenderId: '1027139795680',
    projectId: 'flutter-phone-verificati-35f25',
    authDomain: 'flutter-phone-verificati-35f25.firebaseapp.com',
    storageBucket: 'flutter-phone-verificati-35f25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPNrU_TNbdmlbDAjQWlOSRqvlIF1cWPg',
    appId: '1:1027139795680:android:d4696836033616e6776e85',
    messagingSenderId: '1027139795680',
    projectId: 'flutter-phone-verificati-35f25',
    storageBucket: 'flutter-phone-verificati-35f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1pLFWavLGTyq-FOlAzaZvhss7k0-0mfk',
    appId: '1:1027139795680:ios:c3094f20e71885a3776e85',
    messagingSenderId: '1027139795680',
    projectId: 'flutter-phone-verificati-35f25',
    storageBucket: 'flutter-phone-verificati-35f25.appspot.com',
    androidClientId: '1027139795680-6o7nvnapsvei42ij16ceg0b220lhvjon.apps.googleusercontent.com',
    iosClientId: '1027139795680-82og06domr8ki845o5vj1t53tjg62aut.apps.googleusercontent.com',
    iosBundleId: 'com.example.vote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1pLFWavLGTyq-FOlAzaZvhss7k0-0mfk',
    appId: '1:1027139795680:ios:c3094f20e71885a3776e85',
    messagingSenderId: '1027139795680',
    projectId: 'flutter-phone-verificati-35f25',
    storageBucket: 'flutter-phone-verificati-35f25.appspot.com',
    androidClientId: '1027139795680-6o7nvnapsvei42ij16ceg0b220lhvjon.apps.googleusercontent.com',
    iosClientId: '1027139795680-82og06domr8ki845o5vj1t53tjg62aut.apps.googleusercontent.com',
    iosBundleId: 'com.example.vote',
  );
}
